In [10]:
from dataset import Dataset
import logging
import napari
import matplotlib.pyplot as plt
from segmentation import SegmentNuclei, SegmentCytoplasm

logging.basicConfig(level=logging.DEBUG)


d1 = Dataset(name="lumbar_1")
d1.load_nuclei()
d1.load_cytoplasm()
# d1.load_other_channel(channel="green")
d1.load_gene_expression()
df = d1.gene_expression

idx = list()
for i, gene in df.iterrows():
    if gene.x > 6000 and gene.x <= 8000:
        if gene.y > 5000 and gene.y <= 6000:
            idx.append(i)
df = df.iloc[idx]
df.x = df.x - 6000
df.y = df.y - 5000
d1.gene_expression = df

d1.images["Cytoplasm"] = d1.images["Cytoplasm"][5000:6000, 6000:8000]

d1.images["Nuclei"] = d1.images["Nuclei"][5000:6000, 6000:8000]

C:\Users\jetja\miniconda3\envs\scSpatial\lib\site-packages\pandas\core\generic.py:5516: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [3]:
seg = SegmentCytoplasm(size=120, flow_threshold=0.4, mask_threshold=0)
seg.run(d1)

INFO:cellpose.core:>>>> using CPU
INFO:cellpose.models:~~~ FINDING MASKS ~~~
INFO:cellpose.models:>>>> TOTAL TIME 73.14 sec


In [8]:
viewer.window.add_dock_widget(colorObjectWidget(d1, viewer))

NameError: name 'viewer' is not defined

In [7]:
import pandas as pd
gene_map = list()
for i, gene in d1.gene_expression.iterrows():
    object_id = seg.objects[int(gene.y), int(gene.x)]
    gene_map.append((gene.gene, object_id, 1))

df = pd.DataFrame(gene_map, columns=["gene", "object_id", "value"])
df = df.pivot_table(index="object_id", columns="gene", values="value", fill_value=0, aggfunc=sum)
df
#seg.gene_expression = df

gene       Adamts5  Aif1  Calb2  Cplx1  Cpne4  Crabp1  Csf1r  Elavl4  Gad2  \
object_id                                                                    
0                8     1      2      3      0       0      4       1     0   
1                0     0      0      0      1       0      1       0     0   
3                0     0      0      0      0       0      0       1     0   
4                0     0      0      0      1       0      0       0     0   
5                0     0      0      0      0       0      0       0     0   
6                0     0      0      0      0       0      0       0     0   
7                0     1      0      0      0       0      0       0     0   
8                0     0      0      0      0       0      0       0     0   
12               0     1      0      1      0       0      0       0     1   
13               0     1      0      0      0       0      0       0     0   
14               0     0      0      0      1       0      0       0     0   
16               1     1      0      0      0       0      0       0     0   
17               0     0      0      0      1       0      0       0     0   
19               0     0      0      0      0       0      0       0     1   
20               0     0      0      0      0       0      0       1     0   
23               3     1      0      0      0       0      0       0     0   
25               0     1      0      0      0       0      1       1     0   
30               0     1      0      0      0       0      0       0     0   
31               0     0      0      0      0       0      0       0     0   
32               0     0      0      0      0       0      0       0     0   
33               0     0      0      0      0       0      0       0     0   
34               0     0      0      2      0       1      0       0     0   
35               0     0      0      0      0       0      1       0     1   
36               0     0      0      0      0       0      0       0     0   
37               0     1      0      0      0       0      0       0     0   
38               0     0      0      0      0       0      0       1     0   
42               1     0      0      0      0       0      0       0     0   
46               0     0      0      0      1       0      0       0     0   
48               0     0      0      0      0       0      0       0     0   
49               0     0      0      0      0       1      0       0     0   
50               0     0      0      0      0       0      0       0     0   
51               0     0      1      1      0       1      1       1     0   
56               0     0      0      0      0       0      0       0     1   
59               0     0      0      1      0       0      0       0     0   
60               0     0      0      0      0       0      0       0     0   
62               0     0      0      0      1       0      0       0     0   
63               0     0      0      0      0       0      0       0     0   
65               0     0      0      0      1       0      0       0     0   
68               0     0      0      0      0       0      0       0     0   

gene       Gal  ...  Npy2r  Nts  Pdyn  Slc32a1  Slc6a5  Sorcs3  Spp1  Sstr2  \
object_id       ...                                                           
0            0  ...      0    0     0        0       0       4     1      0   
1            0  ...      0    0     0        0       0       0     0      0   
3            0  ...      0    0     0        0       0       0     0      0   
4            0  ...      0    0     0        0       0       0     0      0   
5            0  ...      0    0     0        0       0       0     1      0   
6            0  ...      0    0     0        0       0       1     0      0   
7            0  ...      0    0     0        0       0       0     0      0   
8            0  ...      0    0     0        0       0       0     0      0   
12         

In [ ]:
seg.map_genes(d1)

In [4]:
d1.segmentation.gene_expression

value                                                      ...  \
gene      Adamts5 Aif1 Calb2 Cplx1 Cpne4 Crabp1 Csf1r Elavl4 Gad2 Gal  ...   
object_id                                                              ...   
0               8    1     2     3     0      0     4      1    0   0  ...   
1               0    0     0     0     1      0     1      0    0   0  ...   
3               0    0     0     0     0      0     0      1    0   0  ...   
4               0    0     0     0     1      0     0      0    0   0  ...   
5               0    0     0     0     0      0     0      0    0   0  ...   
6               0    0     0     0     0      0     0      0    0   0  ...   
7               0    1     0     0     0      0     0      0    0   0  ...   
8               0    0     0     0     0      0     0      0    0   0  ...   
12              0    1     0     1     0      0     0      0    1   0  ...   
13              0    1     0     0     0      0     0      0    0   0  ...   
14              0    0     0     0     1      0     0      0    0   0  ...   
16              1    1     0     0     0      0     0      0    0   0  ...   
17              0    0     0     0     1      0     0      0    0   0  ...   
19              0    0     0     0     0      0     0      0    1   0  ...   
20              0    0     0     0     0      0     0      1    0   0  ...   
23              3    1     0     0     0      0     0      0    0   0  ...   
25              0    1     0     0     0      0     1      1    0   0  ...   
30              0    1     0     0     0      0     0      0    0   0  ...   
31              0    0     0     0     0      0     0      0    0   0  ...   
32              0    0     0     0     0      0     0      0    0   0  ...   
33              0    0     0     0     0      0     0      0    0   0  ...   
34              0    0     0     2     0      1     0      0    0   0  ...   
35              0    0     0     0     0      0     1      0    1   0  ...   
36              0    0     0     0     0      0     0      0    0   0  ...   
37              0    1     0     0     0      0     0      0    0   0  ...   
38              0    0     0     0     0      0     0      1    0   0  ...   
42              1    0     0     0     0      0     0      0    0   0  ...   
46              0    0     0     0     1      0     0      0    0   1  ...   
48              0    0     0     0     0      0     0      0    0   0  ...   
49              0    0     0     0     0      1     0      0    0   0  ...   
50              0    0     0     0     0      0     0      0    0   0  ...   
51              0    0     1     1     0      1     1      1    0   0  ...   
56              0    0     0     0     0      0     0      0    1   0  ...   
59              0    0     0     1     0      0     0      0    0   0  ...   
60              0    0     0     0     0      0     0      0    0   0  ...   
62              0    0     0     0     1      0     0      0    0   0  ...   
63              0    0     0     0     0      0     0      0    0   0  ...   
65              0    0     0     0     1      0     0      0    0   0  ...   
68              0    0     0     0     0      0     0      0    0   0  ...   

                                                                    
gene      Npy2r Nts Pdyn Slc32a1 Slc6a5 Sorcs3 Spp1 Sstr2 Tac2 Trh  
object_id                                                           
0             0   0    0       0      0      4    1     0    0   3  
1             0   0    0       0      0      0    0     0    0   0  
3             0   0    0       0      0      0    0     0    0   0  
4             0   0    0       0      0      0    0     0    0   0  
5             0   0    0       0      0      0    1     0    0   0  
6             0   0    0       0      0      1    0     0    0   0  
7             0   0    0       0      0      0    0     0    0   0  
8             0   0    0       0      0      

In [61]:
import pandas as pd
gene_map = list()
for i, gene in d1.gene_expression.iterrows():
    object_id = d1.segmentation.objects[int(gene.PosY), int(gene.PosX)]
    gene_map.append((gene.Gene, object_id, 1))
df = pd.DataFrame(gene_map, columns=["gene", "object_id", "value"])
df.pivot_table(index="object_id", columns="gene", fill_value=0, aggfunc=sum)

value                                                      ...  \
gene      Adamts5 Aif1 Calb2 Cplx1 Cpne4 Crabp1 Csf1r Elavl4 Gad2 Gal  ...   
object_id                                                              ...   
0               8    1     2     3     0      0     4      1    0   0  ...   
1               0    0     0     0     1      0     1      0    0   0  ...   
3               0    0     0     0     0      0     0      1    0   0  ...   
4               0    0     0     0     1      0     0      0    0   0  ...   
5               0    0     0     0     0      0     0      0    0   0  ...   
6               0    0     0     0     0      0     0      0    0   0  ...   
7               0    1     0     0     0      0     0      0    0   0  ...   
8               0    0     0     0     0      0     0      0    0   0  ...   
12              0    1     0     1     0      0     0      0    1   0  ...   
13              0    1     0     0     0      0     0      0    0   0  ...   
14              0    0     0     0     1      0     0      0    0   0  ...   
16              1    1     0     0     0      0     0      0    0   0  ...   
17              0    0     0     0     1      0     0      0    0   0  ...   
19              0    0     0     0     0      0     0      0    1   0  ...   
20              0    0     0     0     0      0     0      1    0   0  ...   
23              3    1     0     0     0      0     0      0    0   0  ...   
25              0    1     0     0     0      0     1      1    0   0  ...   
30              0    1     0     0     0      0     0      0    0   0  ...   
31              0    0     0     0     0      0     0      0    0   0  ...   
32              0    0     0     0     0      0     0      0    0   0  ...   
33              0    0     0     0     0      0     0      0    0   0  ...   
34              0    0     0     2     0      1     0      0    0   0  ...   
35              0    0     0     0     0      0     1      0    1   0  ...   
36              0    0     0     0     0      0     0      0    0   0  ...   
37              0    1     0     0     0      0     0      0    0   0  ...   
38              0    0     0     0     0      0     0      1    0   0  ...   
42              1    0     0     0     0      0     0      0    0   0  ...   
46              0    0     0     0     1      0     0      0    0   1  ...   
48              0    0     0     0     0      0     0      0    0   0  ...   
49              0    0     0     0     0      1     0      0    0   0  ...   
50              0    0     0     0     0      0     0      0    0   0  ...   
51              0    0     1     1     0      1     1      1    0   0  ...   
56              0    0     0     0     0      0     0      0    1   0  ...   
59              0    0     0     1     0      0     0      0    0   0  ...   
60              0    0     0     0     0      0     0      0    0   0  ...   
62              0    0     0     0     1      0     0      0    0   0  ...   
63              0    0     0     0     0      0     0      0    0   0  ...   
65              0    0     0     0     1      0     0      0    0   0  ...   
68              0    0     0     0     0      0     0      0    0   0  ...   

                                                                    
gene      Npy2r Nts Pdyn Slc32a1 Slc6a5 Sorcs3 Spp1 Sstr2 Tac2 Trh  
object_id                                                           
0             0   0    0       0      0      4    1     0    0   3  
1             0   0    0       0      0      0    0     0    0   0  
3             0   0    0       0      0      0    0     0    0   0  
4             0   0    0       0      0      0    0     0    0   0  
5             0   0    0       0      0      0    1     0    0   0  
6             0   0    0       0      0      1    0     0    0   0  
7             0   0    0       0      0      0    0     0    0   0  
8             0   0    0       0      0      

In [ ]:
viewer = napari.Viewer(axis_labels=["Dorsoventral", "Mediolateral"])

viewer.add_image(d1.images["Nuclei"], name="Nuclei", colormap="yellow")
viewer.add_image(
    d1.images["Cytoplasm"], name="Cytoplasm", blending="additive", colormap="cyan"
)
viewer.add_points(data=list(zip(df.PosY, df.PosX)), properties=df, text="Gene")

viewer.add_labels(d1.segmentation.objects)

In [74]:
from vispy.color.colormap import get_colormap
import numpy as np

In [85]:
cm = get_colormap("gist_ncar")
cm

In [86]:
cat_col = d1.gene_expression.gene.astype("category")
colors = cm.map(cat_col.cat.codes/max(cat_col.cat.codes))

In [87]:
color_map = dict(zip(cat_col.cat.categories, colors))

In [88]:
list(d1.gene_expression.gene.map(color_map))

[array([0.22479278, 0.89653188, 0.        , 1.        ]),
 array([0.92876345, 1.        , 0.06234556, 1.        ]),
 array([0.22479278, 0.89653188, 0.        , 1.        ]),
 array([0.        , 0.44278041, 1.        , 1.        ]),
 array([0.22479278, 0.89653188, 0.        , 1.        ]),
 array([0.22479278, 0.89653188, 0.        , 1.        ]),
 array([0.22479278, 0.89653188, 0.        , 1.        ]),
 array([0.        , 0.44278041, 1.        , 1.        ]),
 array([0.60751623, 1.        , 0.12490198, 1.        ]),
 array([0.22479278, 0.89653188, 0.        , 1.        ]),
 array([0.22479278, 0.89653188, 0.        , 1.        ]),
 array([0.60751623, 1.        , 0.12490198, 1.        ]),
 array([0.92876345, 1.        , 0.06234556, 1.        ]),
 array([0.        , 0.98203045, 0.49128905, 1.        ]),
 array([0.        , 0.98930609, 0.76846606, 1.        ]),
 array([0.22479278, 0.89653188, 0.        , 1.        ]),
 array([0.22479278, 0.89653188, 0.        , 1.        ]),
 array([0.    

In [1]:
import scanpy as sc


In [2]:
adata = sc.read("C:/Users/jonja158/OneDrive/Dokument/Neuro/Projects/In situ sequencing/reference datasets/final_meta_dataset.h5ad")

In [18]:
cell_types = "OPC''Oligo Progen-1''Oligo Progen-2''Oligos-1''Oligos-2''Schwann''Peripheral glia/BC derivative''Meninges-1''Meninges-2''Ependymal''Astrocytes-1''Astrocytes-2''Endothelial''Pericytes''Microglia''MN-alpha''MN-gamma''PGC''CSF-cN''Excit-1''Excit-2''Excit-3''Excit-4''Excit-5''Excit-6''Excit-7''Excit-8''Excit-9''Excit-10''Excit-11''Excit-12''Excit-13''Excit-14''Excit-15''Excit-16''Excit-17''Excit-18''Excit-19''Excit-20''Inhib-1''Inhib-2''Inhib-3''Inhib-4''Inhib-5''Inhib-6''Inhib-7''Inhib-8''Inhib-9''Inhib-10''Inhib-11''Inhib-12''Inhib-13''Inhib-14''Excit-21''Excit-22''Excit-23''Excit-24''Excit-25''Excit-26''Excit-27''Excit-28''Excit-29''Excit-30''Inhib-15''Inhib-16''Inhib-17''Inhib-18''Inhib-19''Inhib-20''Inhib-21''Excit-31''Excit-32''Excit-33''Excit-34''Excit-35''Excit-36''Excit-37''Excit-38''Inhib-22''Inhib-23''Inhib-24''Inhib-25''Inhib-26''Inhib-27"
cell_types = cell_types.split("''")
cell_type_map = dict(zip(range(0,84), cell_types))

In [19]:
adata.obs["final_cluster_assignment"] = adata.obs["final_cluster_assignment"].map(cell_type_map)

In [ ]:
adata.write("C:/Users/jonja158/OneDrive/Dokument/Neuro/Projects/In situ sequencing/reference datasets/final_meta_dataset_fixed.h5ad")

C:\Users\jonja158\Anaconda3\envs\scSpatial\lib\site-packages\anndata\_core\anndata.py:1228: FutureWarning: The `inplace` parameter in pandas.Categorical.reorder_categories is deprecated and will be removed in a future version. Reordering categories will always return a new Categorical object.
  c.reorder_categories(natsorted(c.categories), inplace=True)
... storing 'orig.ident' as categorical
C:\Users\jonja158\Anaconda3\envs\scSpatial\lib\site-packages\anndata\_core\anndata.py:1228: FutureWarning: The `inplace` parameter in pandas.Categorical.reorder_categories is deprecated and will be removed in a future version. Reordering categories will always return a new Categorical object.
  c.reorder_categories(natsorted(c.categories), inplace=True)
... storing 'run' as categorical
C:\Users\jonja158\Anaconda3\envs\scSpatial\lib\site-packages\anndata\_core\anndata.py:1228: FutureWarning: The `inplace` parameter in pandas.Categorical.reorder_categories is deprecated and will be removed in a futu